/* 
 * Copyright 2015 Nils Hoffmann.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package circularlayouts.swing;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Nils Hoffmann
 */
public class CircularLayoutComponent extends javax.swing.JPanel implements ChangeListener {

    private CircularLayoutPanel panel;
    private double segmentSize = 45.0;
    private double targetMargin = 5.0;
    private double sourceMargin = 0.0;
    private double segmentMargin = 0.05;
    private double segmentAngle = 0.0;

    /**
     * Creates new form CircularLayoutComponent
     */
    public CircularLayoutComponent() {
        initComponents();
        setOpaque(true);
        setDoubleBuffered(true);
        segmentSizeSpinner.addChangeListener(this);
        targetMarginSpinner.addChangeListener(this);
        sourceMarginSpinner.addChangeListener(this);
        segmentMarginSpinner.addChangeListener(this);
        segmentAngleSpinner.addChangeListener(this);
    }

    public void setData(double[][] data) {
        if (panel != null) {
            remove(panel);
        }
        panel = new CircularLayoutPanel();
        add(panel, BorderLayout.CENTER);
        panel.setData(data);
    }

    public double getSegmentSize() {
        return segmentSize;
    }

    public void setSegmentSize(double segmentSize) {
        this.segmentSize = segmentSize;
        if (this.panel != null) {
            this.panel.setSegmentSize(segmentSize);
        }
    }

    public double getSegmentAngle() {
        return segmentAngle;
    }

    public void setSegmentAngle(double segmentAngle) {
        this.segmentAngle = segmentAngle;
        if (this.panel != null) {
            this.panel.setSegmentAngle(segmentAngle);
        }
    }

    public double getTargetMargin() {
        return targetMargin;
    }

    public void setTargetMargin(double margin) {
        this.targetMargin = margin;
        if (this.panel != null) {
            this.panel.setTargetMargin(margin);
        }
    }

    public double getSegmentMargin() {
        return segmentMargin;
    }

    public void setSegmentMargin(double margin) {
        this.segmentMargin = margin;
        if (this.panel != null) {
            this.panel.setSegmentMargin(margin);
        }
    }

    public double getSourceMargin() {
        return sourceMargin;
    }

    public void setSourceMargin(double margin) {
        this.sourceMargin = margin;
        if (this.panel != null) {
            this.panel.setSourceMargin(margin);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        segmentSizeSpinner = new javax.swing.JSpinner();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel4 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        segmentMarginSpinner = new javax.swing.JSpinner();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel5 = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        segmentAngleSpinner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel3 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        sourceMarginSpinner = new javax.swing.JSpinner();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel2 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        targetMarginSpinner = new javax.swing.JSpinner();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jCheckBox1 = new javax.swing.JCheckBox();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.add(filler9);

        jButton1.setText("To SVG");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jLabel1.setText("Segment Size");
        jToolBar1.add(jLabel1);
        jToolBar1.add(filler2);

        segmentSizeSpinner.setValue(getSegmentSize());
        jToolBar1.add(segmentSizeSpinner);
        jToolBar1.add(filler1);

        jLabel4.setText("Segment Margin");
        jToolBar1.add(jLabel4);
        jToolBar1.add(filler6);

        segmentMarginSpinner.setModel(new javax.swing.SpinnerNumberModel(0.05d, 0.0d, 1.0d, 0.01d));
        jToolBar1.add(segmentMarginSpinner);
        segmentMarginSpinner.setValue(getSegmentMargin());
        jToolBar1.add(filler10);

        jLabel5.setText("Segment Angle");
        jToolBar1.add(jLabel5);
        jToolBar1.add(filler11);

        segmentAngleSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.01d));
        jToolBar1.add(segmentAngleSpinner);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(filler4);

        jLabel3.setText("Source Margin");
        jToolBar1.add(jLabel3);
        jToolBar1.add(filler7);
        jToolBar1.add(sourceMarginSpinner);
        sourceMarginSpinner.setValue(getSourceMargin());
        jToolBar1.add(filler8);

        jLabel2.setText("Target Margin");
        jToolBar1.add(jLabel2);
        jToolBar1.add(filler3);

        targetMarginSpinner.setValue(getTargetMargin());
        jToolBar1.add(targetMarginSpinner);
        jToolBar1.add(filler5);

        jCheckBox1.setText("Animate");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox1);
        jToolBar1.add(filler12);
        jToolBar1.add(filler13);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        this.panel.setSuspend(!jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.panel.saveToSVG(File.createTempFile("CircularLayout", ".svg"));
        } catch (IOException ex) {
            Logger.getLogger(CircularLayoutComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner segmentAngleSpinner;
    private javax.swing.JSpinner segmentMarginSpinner;
    private javax.swing.JSpinner segmentSizeSpinner;
    private javax.swing.JSpinner sourceMarginSpinner;
    private javax.swing.JSpinner targetMarginSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent ce) {
        if (ce.getSource().equals(segmentSizeSpinner)) {
            setSegmentSize(Double.parseDouble(segmentSizeSpinner.getValue().toString()));
        } else if (ce.getSource().equals(targetMarginSpinner)) {
            setTargetMargin(Double.parseDouble(targetMarginSpinner.getValue().toString()));
        } else if (ce.getSource().equals(sourceMarginSpinner)) {
            setSourceMargin(Double.parseDouble(sourceMarginSpinner.getValue().toString()));
        } else if (ce.getSource().equals(segmentMarginSpinner)) {
            setSegmentMargin(Double.parseDouble(segmentMarginSpinner.getValue().toString()));
        } else if (ce.getSource().equals(segmentAngleSpinner)) {
            setSegmentAngle(Double.parseDouble(segmentAngleSpinner.getValue().toString()));
        }
    }

}
